"""
Database models for SentinelSOC.
Implements SecurityEvent, SecurityAlert, and DailyMetrics models.
"""
from datetime import datetime, timezone
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def utc_now():
    """Return timezone-aware or clean UTC datetime for database defaults"""
    return datetime.now(timezone.utc)


class SecurityEvent(db.Model):
    """
    Model for security events parsed from authentication and server logs.
    Includes baseline threat classification, risk scoring, and recommendations.
    """
    __tablename__ = 'security_events'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    timestamp = db.Column(db.DateTime, nullable=False, index=True)
    event_type = db.Column(db.String(50), nullable=False, index=True)
    username = db.Column(db.String(100), nullable=True, index=True)
    source_ip = db.Column(db.String(45), nullable=False, index=True)
    destination_ip = db.Column(db.String(45), nullable=True)
    message = db.Column(db.Text, nullable=True)
    
    # Risk and Threat Classification fields (Section 6)
    risk_score = db.Column(db.Integer, default=0, nullable=False, index=True)
    severity = db.Column(db.String(20), default='LOW', nullable=False, index=True)
    detected_threat = db.Column(db.String(100), nullable=True, index=True)
    recommendation = db.Column(db.Text, nullable=True)
    
    status = db.Column(db.String(20), default='processed', nullable=False)
    created_at = db.Column(db.DateTime, default=utc_now, nullable=False)
    
    # Relationship to alerts
    alerts = db.relationship('SecurityAlert', back_populates='event', cascade='all, delete-orphan')
    
    def to_dict(self):
        return {
            'id': self.id,
            'timestamp': self.timestamp.isoformat() if self.timestamp else None,
            'event_type': self.event_type,
            'username': self.username,
            'source_ip': self.source_ip,
            'destination_ip': self.destination_ip,
            'message': self.message,
            'risk_score': self.risk_score,
            'severity': self.severity,
            'detected_threat': self.detected_threat,
            'recommendation': self.recommendation,
            'status': self.status,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }
    
    def __repr__(self):
        return f'<SecurityEvent id={self.id} type={self.event_type} ip={self.source_ip} score={self.risk_score}>'


class SecurityAlert(db.Model):
    """
    Model for consolidated high-fidelity security alerts generated by the threat detection engine.
    """
    __tablename__ = 'security_alerts'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    event_id = db.Column(db.Integer, db.ForeignKey('security_events.id', ondelete='CASCADE'), nullable=False)
    threat_type = db.Column(db.String(100), nullable=False, index=True)
    severity = db.Column(db.String(20), nullable=False, index=True)
    risk_score = db.Column(db.Integer, nullable=False, index=True)
    reason = db.Column(db.Text, nullable=False)
    recommended_action = db.Column(db.Text, nullable=True)
    investigation_notes = db.Column(db.Text, nullable=True)
    status = db.Column(db.String(20), default='open', nullable=False, index=True)  # open, investigating, resolved
    source_ip = db.Column(db.String(45), nullable=True, index=True)
    affected_users = db.Column(db.String(500), nullable=True)
    detection_timestamp = db.Column(db.DateTime, default=utc_now, nullable=False, index=True)
    resolved_at = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, default=utc_now, nullable=False)
    
    # Relationship to parent event
    event = db.relationship('SecurityEvent', back_populates='alerts')
    
    def to_dict(self):
        return {
            'id': self.id,
            'event_id': self.event_id,
            'threat_type': self.threat_type,
            'severity': self.severity,
            'risk_score': self.risk_score,
            'reason': self.reason,
            'recommended_action': self.recommended_action,
            'investigation_notes': self.investigation_notes,
            'status': self.status,
            'source_ip': self.source_ip,
            'affected_users': self.affected_users,
            'detection_timestamp': self.detection_timestamp.isoformat() if self.detection_timestamp else None,
            'resolved_at': self.resolved_at.isoformat() if self.resolved_at else None,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }
    
    def __repr__(self):
        return f'<SecurityAlert id={self.id} threat={self.threat_type} sev={self.severity} score={self.risk_score}>'


class DailyMetrics(db.Model):
    """
    Model for caching aggregated daily security posture metrics.
    """
    __tablename__ = 'daily_metrics'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    date = db.Column(db.Date, unique=True, nullable=False, index=True)
    total_events = db.Column(db.Integer, default=0, nullable=False)
    total_alerts = db.Column(db.Integer, default=0, nullable=False)
    critical_threats = db.Column(db.Integer, default=0, nullable=False)
    high_threats = db.Column(db.Integer, default=0, nullable=False)
    medium_threats = db.Column(db.Integer, default=0, nullable=False)
    low_threats = db.Column(db.Integer, default=0, nullable=False)
    unique_ips = db.Column(db.Integer, default=0, nullable=False)
    unique_users = db.Column(db.Integer, default=0, nullable=False)
    top_threat_type = db.Column(db.String(100), nullable=True)
    created_at = db.Column(db.DateTime, default=utc_now, nullable=False)
    
    def to_dict(self):
        return {
            'id': self.id,
            'date': str(self.date),
            'total_events': self.total_events,
            'total_alerts': self.total_alerts,
            'critical_threats': self.critical_threats,
            'high_threats': self.high_threats,
            'medium_threats': self.medium_threats,
            'low_threats': self.low_threats,
            'unique_ips': self.unique_ips,
            'unique_users': self.unique_users,
            'top_threat_type': self.top_threat_type,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }
    
    def __repr__(self):
        return f'<DailyMetrics date={self.date} events={self.total_events} alerts={self.total_alerts}>'
